# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "https://stirring-stardust-d51df6.netlify.app/*"
  to = "https://ttm.pinata.cloud/:splat"
  status = 301
  force = true

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false