# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/ipfs"
  to = "https://ttm.pinata.cloud/ipfs"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false